# core/reporter.py
from datetime import datetime

def generate_markdown_report(target, findings, output_file="report.md"):
    """Generate Markdown security report"""
    
    # Count by severity
    critical = len([f for f in findings if f.get('severity') == 'Critical' and f.get('status') in ['MISSING', 'FOUND']])
    medium = len([f for f in findings if f.get('severity') == 'Medium' and f.get('status') in ['MISSING', 'FOUND']])
    info = len([f for f in findings if f.get('severity') == 'Info'])
    
    report = f"""# Web Security Scan Report

**Target:** {target}  
**Date:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}  
**Scanner:** Lite Web Scanner (Educational Project)

---

## Summary

| Severity | Count |
|----------|-------|
| Critical | {critical} |
| Medium | {medium} |
| Info | {info} |

---

## Findings

"""
    # Missing headers
    missing_headers = [f for f in findings if f.get('header') and f['status'] == 'MISSING']
    if missing_headers:
        report += "### Missing Security Headers\n\n"
        for item in missing_headers:
            report += f"- **{item['header']}**: {item['info']}\n"
        report += "\n"
    
    # Exposed files
    found_files = [f for f in findings if f.get('file') and f['status'] == 'FOUND']
    if found_files:
        report += "### Exposed Sensitive Files\n\n"
        for item in found_files:
            report += f"- **{item['file']}**: {item['info']}\n"
            report += f"  - URL: `{item['url']}`\n"
        report += "\n"
    
    if not missing_headers and not found_files:
        report += "No critical issues found during this scan.\n\n"
    
    report += """---
> Disclaimer: This report was generated by an educational tool. 
> Results should be verified manually.
"""
    
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(report)
    
    return output_file
